sudo: false
language: node_js
node_js:
- '0.12'
- '6'
env:
  global:
  - SAUCE_USERNAME=devpaul
  - secure: DzKXMmyy+ETDJKoMiE1lEyiV1y1es694WPU0bizcgYSAq8eP7ln0FyGJoQ2VYibEYiedrxOwNijT/1o76VttYKO4R31+Lno35VF9zXisOmP3hrtFhKgIz7u0low7J1otC0AKO1Kbz36kFIA7bHxUGJB69ANDf5q5REu3vLKBGtM3/daOxQozEtBadK8EeVkOliHZ857Ebu+iUnxanatyme1vFcMkpydSrz4pWLy9KN7mY15Gogr8Tz/eSm4yfc1WidEMLXJqx9YxdN8L5IYLJfdZegOKF9h/zFxK/X2Qrlamb50BRwdKkAcg3nB2ByQom41O/DIPx84KYA7/tLAzvOdbF3H4lbR5stKJtmWyW9aBI10OsJszng1r78fSHW+Fq3NW08QuCRHts8i2H0QnMB2hzivM24kCIKi1a9hdZphEVBsyJ8b+1+9W1r3kAVC9wWq+C6MIInz2dtKxQhGE5FNC/WPJqFzGKHtXjCSHkbPwXB30M7H1vWPxhmfNgKECgkpN9MSjHqsm+25ls5AJ0oKKqvmdWt5pho3/wy8RIti5elQzpwPj8vbil1qhPZJhgtyVbOphuA8oZQs9bVCssYvkDbUn7+UfhuQHX9alOSbNEYwa2jHIRyPzI+3HU7vjwLzOCkla74zhw1rKTngzpwCGRLuzsgOKdXMfdynBJXA=
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
script: grunt test-ci
