sudo: false
language: node_js
node_js:
  - '0.12'
  - '6'
env:
  global:
    secure: FQxrT+Klxpki/ErcYEy++BsB8oHX8l1TXmIyTAH99DSrCpG43HoP9ufUw3fRSSaIpbfHWb7uNmPIB7NsqWQhzME8XhQwQ7MW7W8RHRsqMcuSDxbZK8d6YaTv90Ufeeo1HRS7jpZSn2SkojgQPsLDBWQZU0eOj66JOEuvpsxEm6/v4off/Mr5QDjmfNinDFeGsuJJmfbEHjyHmsMj5EUe3OCZR7xIZgiXAL2KKR7bWTeMf0meVphpcTb7WbPG5teZYR0egDLIUPuNvB8rYKHlHeBLGFuv7wqhafkzJeuj8UazYUd+glWqYO74estxRfxpiNGZNbcmpMEmP8X0CyHMJ4ta2otqVdsv7s8FhUXEJiSSPAzUhI9qk/kRdNhTgfHIUDF6Tdb339aah57///CLLphFVeogicMHTj0EUcDQXYQlYPbDq68i14spFGwGwQf81mHe4DkVp2pBwyTpBOwvtpyQwi2przOY8FIt7jNvP+5Sx+RT+0pkT/zNQVdmTrU3uGf+22cZDLsBuhMIRh7lFkFhiQSm92aOveeoaRM4CQvF3th6lDx16LChaVLngdgrGSf2Rus80r2FwD1m9AcyiDv34LDhD0e15QhFhoNzHb2ZNrkPREuFoMN1UtmNex0hXWOyOVJ3Il46an8R4Lw8rgeK/g8IDWO2yjZwm2lsJOY=
cache:
  directories:
    - node_modules
before_script:
   - npm install -g grunt-cli
script: grunt test-ci
